version: '3.8'

services:
  app:
    build:
        dockerfile: Dockerfile
        context: .
    ports:
        - '5050:5050'
    networks:
            - local-net
    env_file:
            - .logs.env
    volumes:
        - logs:/tmp/logs
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
            driver: none
    networks:
            - local-net
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
    logs:

networks:
    local-net:
        name: local-net
        driver: bridge