version: "3"
services:
    kibana:
        image: "docker.elastic.co/kibana/kibana:7.2.0"
        ports:
            - "5601:5601"
        networks:
            - local-net
        logging:
            driver: none
    log-manager:
        image: audio35444/log-emma-driver:v0.1.0
        environment:
            - "LOG_INDEX=logs"
            - "LOG_PATH=/tmp/logs/microservice.log"
            - "ELASTIC_URI=http://es-container:9200"
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        networks:
            - local-net
        logging:
            driver: none
        volumes:
            - logs:/tmp/logs
    elasticsearch:
        container_name: es-container
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - xpack.security.enabled=false
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
        networks:
            - local-net
        logging:
            driver: none
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

volumes:
    logs:
    elasticsearch_data:

networks:
    local-net:
        name: local-net
        driver: bridge